Utkarsh : Directory restructuring

diff --git a/env-setup b/env-setup
--- a/env-setup
+++ b/env-setup
@@ -13,31 +13,27 @@ if [ "$PYTHON_VERSION" != "$(cat python_version.tmp)" ]; then
 	echo "Exiting"
 else
 	echo "Python version Checked"
-fi
-
-rm -rf python_version.tmp
-
-
-if [ -f venv.tmp ] ; then
+	rm -rf python_version.tmp
+	
+	if [ -f venv.tmp ] ; then
+		rm -rf venv.tmp
+	fi
+	
+	echo "$VIRTUAL_ENV" | sed -e 's/\/.*\///g' > venv.tmp
+	if [ ! -s venv.tmp ]; then
+		echo "FAILED : Virtual env not installed"
+		echo "To install virtual env run apt install python3.8-venv"
+		echo "FAILED"
+		exit 1
+	fi
+	
+	if [ "storage-env" != "$(cat venv.tmp)" ]; then
+		source ${BASE_DIR}/.storage-env/bin/activate
+		python3 -m pip install -r requirements.txt
+	fi
 	rm -rf venv.tmp
+
+	echo "Storage-env Virtual Environment activated"
+	echo 
+	echo "DONE"
 fi
-echo "$VIRTUAL_ENV" | sed -e 's/\/.*\///g' > venv.tmp
-
-if [ ! -s venv.tmp ]; then
-	echo "FAILED : Virtual env not installed"
-	echo "To install virtual env run apt install python3.8-venv"
-	echo "FAILED"
-	exit 1
-fi
-
-if [ "storage-env" != "$(cat venv.tmp)" ]; then
-	#python3 -m venv .storage-env
-	#activate
-	source ${BASE_DIR}/.storage-env/bin/activate
-fi
-
-rm -rf venv.tmp
-echo "Storage-env Virtual Environment activated"
-
-echo 
-echo "DONE"
