Utkarsh : Usage of api endpoint (api_obj) in main/views.py

diff --git a/env-setup b/env-setup
--- a/env-setup
+++ b/env-setup
@@ -1,39 +1,34 @@
 BASE_DIR=${PWD}/
-PYTHON_VERSION="Python 3.8.10"
+#PYTHON_VERSION="Python 3.*"
 
 if [ -f "python_version.tmp" ]; then
 	rm -rf python_version.tmp
 fi
 python3 --version > python_version.tmp
 
-if [ "$PYTHON_VERSION" != "$(cat python_version.tmp)" ]; then
-	echo "FAILURE :: Incorrect Python version installed"
-	echo "Current Python Version : $(cat python_version.tmp)"
-	echo "Required version       : $PYTHON_VERSION"
-	echo "Exiting"
-else
-	echo "Python version Checked"
-	rm -rf python_version.tmp
+echo "Python version Checked"
+rm -rf python_version.tmp
 	
-	if [ -f venv.tmp ] ; then
-		rm -rf venv.tmp
-	fi
-	
-	echo "$VIRTUAL_ENV" | sed -e 's/\/.*\///g' > venv.tmp
-	if [ ! -s venv.tmp ]; then
-		echo "FAILED : Virtual env not installed"
-		echo "To install virtual env run apt install python3.8-venv"
-		echo "FAILED"
-		exit 1
-	fi
-	
-	if [ "storage-env" != "$(cat venv.tmp)" ]; then
-		source ${BASE_DIR}/.storage-env/bin/activate
-		python3 -m pip install -r requirements.txt
-	fi
+if [ -f venv.tmp ] ; then
 	rm -rf venv.tmp
-
-	echo "Storage-env Virtual Environment activated"
-	echo 
-	echo "DONE"
 fi
+	
+echo "$VIRTUAL_ENV" | sed -e 's/\/.*\///g' > venv.tmp
+if [ ! -s venv.tmp ]; then
+	echo "FAILED : Virtual env not installed"
+	echo "To install virtual env run apt install python3.8-venv"
+	echo "FAILED"
+	exit 1
+fi
+	
+if [ "storage-env" != "$(cat venv.tmp)" ]; then
+	source ${BASE_DIR}/.storage-env/bin/activate
+	python3 -m pip install -r requirements.txt
+fi
+rm -rf venv.tmp
+
+export PYTHONPATH=${PWD}/../:$PYTHONPATH
+
+echo "Storage-env Virtual Environment activated"
+echo 
+echo "DONE"
